### ISSUE TITLE
.date, .tags and .comments icons do not show up in archives

### ISSUE THREAD

**Issue by 3c7** [macjasp/cleanpress#6]
Hey,

i believe there are some css tags missing in _archive.scss.

regular _archive.scss

``` css
.meta{
  color: $color-gray02;
  font-size: 0.9em;
  line-height: 2;
  margin-top: 15px;
  @media screen and (max-width: 600px){
    display: none;
  }
  span{
    margin-right: 30px;
    @include inline-block;
    &:before{
      color: $color-gray03;
      font: 1.3em $font-icon;
      padding-right: 10px;
    }
  }
  a{
    color: $color-gray02;
    @include transition(0.3s);
    &:hover{
      color: $color-gray01;
    }
  }
  .date:before{content: "\f073";}
  .tags:before{content: "\f02c";}
  .comments:before{content: "\f075";
}
```

changed _archive.scss

``` css
.meta{
  color: $color-gray02;
  font-size: 0.9em;
  line-height: 2;
  margin-top: 15px;
  @media screen and (max-width: 600px){
    display: none;
  }
  span{
    margin-right: 30px;
    @include inline-block;
    &:before{
      color: $color-gray03;
      font: 1.3em $font-icon;
      padding-right: 10px;
    }
  }
  a{
    color: $color-gray02;
    @include transition(0.3s);
    &:hover{
      color: $color-gray01;
    }
  }
  .date, .tags, .comments {
    padding-left: 30px;
    position: relative;
    &:before{
      color: $color-gray02;
      font: 1.3em $font-icon;
      line-height: 1.6em;
      position: absolute;
      left: 0;
    }
  }  
  .date:before{content: "\f073";}
  .tags:before{content: "\f02c";}
  .comments:before{content: "\f075";
}
```

Maybe I just screwed something up, but this made the difference:
![1](https://f.cloud.github.com/assets/2846609/1212062/bd2a0b90-2612-11e3-963a-97f6439e0046.png)
![2](https://f.cloud.github.com/assets/2846609/1212063/bd2e8486-2612-11e3-8bb0-fc2fc0245606.png)

Best Regards
3c7
